language: java
sudo: false
jdk:
  - openjdk10
matrix:
include:
  - jdk: openjdk10
    before_install:
      - rm "${JAVA_HOME}/lib/security/cacerts"
      - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
os:
  - linux
cache:
  directories:
    - $HOME/.m2
script:
  - ./build.sh
after_success:
  - mvn coveralls:report
