language: java
sudo: false
jdk:
- oraclejdk8
os:
- linux
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - MAVEN_OPTS="-XX:MaxPermSize=2g -Xmx4g"
  - JAVA_OPTS="-XX:MaxPermSize=2g -Xmx4g"
script:
- ./build.sh
after_success:
- mvn coveralls:report
