language: java
sudo: false
jdk:
  - oraclejdk9
  - openjdk10
  - oraclejdk10
os:
- linux
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - MAVEN_OPTS="-Xmx4g"
  - JAVA_OPTS="-Xmx4g"
script:
- ./build.sh
after_success:
- mvn coveralls:report
